name: rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build
        continue-on-error: true
        run: cargo build --verbose --release --lib --examples

      - name: Cache builds
        uses: actions/cache@v3
        with:
          path: target
          # key: ${{ runner.os }}-builds-${{ github.sha }}
          key: ${{ runner.os }}-builds

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
<<<<<<< HEAD:.github/workflows/linux.yml
          name: rust-build
          path: target/release/
=======
          name: rust-build-${{ matrix.os }}
          path: target/debug/
>>>>>>> f62d64a (test windows too):.github/workflows/build.yml

  test:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/download-artifact@v3
        with:
<<<<<<< HEAD:.github/workflows/linux.yml
          name: rust-build
          path: target/release

      - name: Make example executable
        run: chmod +x target/release/examples/compile
=======
          name: rust-build-${{ matrix.os }}
          path: target/debug

      - name: Make example executable
        if: matrix.os == 'ubuntu-latest'
        run: chmod +x target/debug/examples/compile
>>>>>>> f62d64a (test windows too):.github/workflows/build.yml

      - name: Run example
        run: target/release/examples/compile
