name: rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build
        run: cargo build --verbose --release --lib --examples

      - name: Cache builds
        uses: actions/cache@v3
        with:
          path: target
          # key: ${{ runner.os }}-builds-${{ github.sha }}
          key: ${{ runner.os }}-builds

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rust-build
          path: target/release/

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: rust-build
          path: target/release

      - name: Make example executable
        run: chmod +x target/release/examples/compile

      - name: Run example
        run: target/release/examples/compile
